apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gh-secret-python-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/yangcao/gh-secret-python-1:3e5383bb0112498c1e0e4bb01dee01e409641138@sha256:ffa9e838f432d49ce476a7a866acf0d9508ab33556a3bde3562f4e911d1f1a41
          name: container-image
