apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gh-secret-python-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gh-secret-python-1 
  name: gh-secret-python-1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gh-secret-python-1 
